### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by vtolstov** [yanzay/tbot#7]
when bot added to channel and bot recieves message like @exampleBot /hi
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x65b7a2]

goroutine 50 [running]:
github.com/yanzay/tbot/internal/adapter.(*Bot).adaptUpdates(0xc42000e028, 0xc420102600, 0xc42026cd80)
        /home/vtolstov/go/src/github.com/yanzay/tbot/internal/adapter/adapter.go:74 +0x122
created by github.com/yanzay/tbot/internal/adapter.(*Bot).GetUpdatesChan
        /home/vtolstov/go/src/github.com/yanzay/tbot/internal/adapter/adapter.go:57 +0xee
```

**Comment by yanzay** [comment]
@vtolstov thanks for your report, I'll take it
